<a href="https://colab.research.google.com/github/MarcoLope/PROYECTOO/blob/master/Practica_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.tokenize import RegexpTokenizer
import numpy as np    
from numpy import dot
from numpy.linalg import norm
import scipy as sc
from scipy.spatial import distance
set(stopwords.words('spanish'))
import pandas as pd
import numpy as np
import missingno as msno
%matplotlib inline

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [0]:
stopwords.fileids()
set(stopwords.words('spanish'))
tokenizer = RegexpTokenizer(r'\w+')

**Tokenización**

In [0]:
path = '/content/tweets.csv'
df = pd.read_csv(path, encoding='latin', error_bad_lines=False)
df.head()

TWEET
0  la madrugada de este sabado, dos hombres y una...
1  en china se derrumba hotel donde se mantenia a...
2  una banda hacia creer que su perro estaba enfe...
3  estudiantes del colegio de bachilleres 39, en ...
4  estudiantes de imgenieria quimica de la univer...

In [0]:
texts=[]     
for i in range(0,df['TWEET'].count()):
    texts.append(df['TWEET'][i])
texts

['la madrugada de este sabado, dos hombres y una mujer resultaron lesionados tras registrarse una balacera afuera de un bar ubicado en zona centro de san andres chulula, puebla.',
 'en china se derrumba hotel donde se mantenia a decenas de personas en cuarentena por contacto con infectados por covid-19, se habla de unas 70 personas atrapadas entre los escombros',
 'una banda hacia creer que su perro estaba enfermo y que necesitaban dinero para sus vacunas',
 'estudiantes del colegio de bachilleres 39, en nazareno etla en oaxaca. alumnas encararon y exhibieron carteles a un maestro al que acusaron de acoso',
 'estudiantes de imgenieria quimica de la universidad autonoma de yucatan se pusieron ellos mismos a producir gel antibacterial para abastecer las necesidades de su universidad',
 'la fata morgana es una ilusión óptica que se debe a una inversión de temperatura. la separación regular entre el aire caliente y el aire frÃ\xado (más denso) cerca de la superficie puede actuar como 

In [0]:
print(texts)

['la madrugada de este sabado, dos hombres y una mujer resultaron lesionados tras registrarse una balacera afuera de un bar ubicado en zona centro de san andres chulula, puebla.', 'en china se derrumba hotel donde se mantenia a decenas de personas en cuarentena por contacto con infectados por covid-19, se habla de unas 70 personas atrapadas entre los escombros', 'una banda hacia creer que su perro estaba enfermo y que necesitaban dinero para sus vacunas', 'estudiantes del colegio de bachilleres 39, en nazareno etla en oaxaca. alumnas encararon y exhibieron carteles a un maestro al que acusaron de acoso', 'estudiantes de imgenieria quimica de la universidad autonoma de yucatan se pusieron ellos mismos a producir gel antibacterial para abastecer las necesidades de su universidad', 'la fata morgana es una ilusión óptica que se debe a una inversión de temperatura. la separación regular entre el aire caliente y el aire frÃ\xado (más denso) cerca de la superficie puede actuar como una l

In [0]:
text_token=[]

text_stops= [ [0 for columna in range(0,0)] for fila in range (0,df['TWEET'].count())]
for i in range(0,df['TWEET'].count()):
    text_token.append(tokenizer.tokenize(texts[i].lower()))

for i in range(0,df['TWEET'].count()):
      for word in text_token[i]:
        if word not in stopwords.words('spanish'): text_stops[i].append(word)
text_token
print(text_stops)

[['madrugada', 'sabado', 'dos', 'hombres', 'mujer', 'resultaron', 'lesionados', 'tras', 'registrarse', 'balacera', 'afuera', 'bar', 'ubicado', 'zona', 'centro', 'san', 'andres', 'chulula', 'puebla'], ['china', 'derrumba', 'hotel', 'mantenia', 'decenas', 'personas', 'cuarentena', 'contacto', 'infectados', 'covid', '19', 'habla', 'unas', '70', 'personas', 'atrapadas', 'escombros'], ['banda', 'hacia', 'creer', 'perro', 'enfermo', 'necesitaban', 'dinero', 'vacunas'], ['estudiantes', 'colegio', 'bachilleres', '39', 'nazareno', 'etla', 'oaxaca', 'alumnas', 'encararon', 'exhibieron', 'carteles', 'maestro', 'acusaron', 'acoso'], ['estudiantes', 'imgenieria', 'quimica', 'universidad', 'autonoma', 'yucatan', 'pusieron', 'mismos', 'producir', 'gel', 'antibacterial', 'abastecer', 'necesidades', 'universidad'], ['fata', 'morgana', 'ilusiã³n', 'ã³ptica', 'debe', 'inversiã³n', 'temperatura', 'separaciã³n', 'regular', 'aire', 'caliente', 'aire', 'frã', 'mã', 's', 'denso', 'cerca', 'superficie', 'puede

In [0]:
print(text_token)

[['la', 'madrugada', 'de', 'este', 'sabado', 'dos', 'hombres', 'y', 'una', 'mujer', 'resultaron', 'lesionados', 'tras', 'registrarse', 'una', 'balacera', 'afuera', 'de', 'un', 'bar', 'ubicado', 'en', 'zona', 'centro', 'de', 'san', 'andres', 'chulula', 'puebla'], ['en', 'china', 'se', 'derrumba', 'hotel', 'donde', 'se', 'mantenia', 'a', 'decenas', 'de', 'personas', 'en', 'cuarentena', 'por', 'contacto', 'con', 'infectados', 'por', 'covid', '19', 'se', 'habla', 'de', 'unas', '70', 'personas', 'atrapadas', 'entre', 'los', 'escombros'], ['una', 'banda', 'hacia', 'creer', 'que', 'su', 'perro', 'estaba', 'enfermo', 'y', 'que', 'necesitaban', 'dinero', 'para', 'sus', 'vacunas'], ['estudiantes', 'del', 'colegio', 'de', 'bachilleres', '39', 'en', 'nazareno', 'etla', 'en', 'oaxaca', 'alumnas', 'encararon', 'y', 'exhibieron', 'carteles', 'a', 'un', 'maestro', 'al', 'que', 'acusaron', 'de', 'acoso'], ['estudiantes', 'de', 'imgenieria', 'quimica', 'de', 'la', 'universidad', 'autonoma', 'de', 'yucat

In [0]:
token_wout_stopwords = []
for word in text_token:
  if word not in stopwords.words('spanish'):
    token_wout_stopwords.append(word)

In [0]:
 print(token_wout_stopwords)
 print(len(token_wout_stopwords))

[['la', 'madrugada', 'de', 'este', 'sabado', 'dos', 'hombres', 'y', 'una', 'mujer', 'resultaron', 'lesionados', 'tras', 'registrarse', 'una', 'balacera', 'afuera', 'de', 'un', 'bar', 'ubicado', 'en', 'zona', 'centro', 'de', 'san', 'andres', 'chulula', 'puebla'], ['en', 'china', 'se', 'derrumba', 'hotel', 'donde', 'se', 'mantenia', 'a', 'decenas', 'de', 'personas', 'en', 'cuarentena', 'por', 'contacto', 'con', 'infectados', 'por', 'covid', '19', 'se', 'habla', 'de', 'unas', '70', 'personas', 'atrapadas', 'entre', 'los', 'escombros'], ['una', 'banda', 'hacia', 'creer', 'que', 'su', 'perro', 'estaba', 'enfermo', 'y', 'que', 'necesitaban', 'dinero', 'para', 'sus', 'vacunas'], ['estudiantes', 'del', 'colegio', 'de', 'bachilleres', '39', 'en', 'nazareno', 'etla', 'en', 'oaxaca', 'alumnas', 'encararon', 'y', 'exhibieron', 'carteles', 'a', 'un', 'maestro', 'al', 'que', 'acusaron', 'de', 'acoso'], ['estudiantes', 'de', 'imgenieria', 'quimica', 'de', 'la', 'universidad', 'autonoma', 'de', 'yucat

**Creación de la** **BoW**

In [0]:
dicc_texts={}
for i in range(0,df['TWEET'].count()):
  var='TWEET'+ str(i+1)
  dicc_texts.setdefault(var,text_stops[i])

In [0]:
print(dicc_texts)

{'TWEET1': ['madrugada', 'sabado', 'dos', 'hombres', 'mujer', 'resultaron', 'lesionados', 'tras', 'registrarse', 'balacera', 'afuera', 'bar', 'ubicado', 'zona', 'centro', 'san', 'andres', 'chulula', 'puebla'], 'TWEET2': ['china', 'derrumba', 'hotel', 'mantenia', 'decenas', 'personas', 'cuarentena', 'contacto', 'infectados', 'covid', '19', 'habla', 'unas', '70', 'personas', 'atrapadas', 'escombros'], 'TWEET3': ['banda', 'hacia', 'creer', 'perro', 'enfermo', 'necesitaban', 'dinero', 'vacunas'], 'TWEET4': ['estudiantes', 'colegio', 'bachilleres', '39', 'nazareno', 'etla', 'oaxaca', 'alumnas', 'encararon', 'exhibieron', 'carteles', 'maestro', 'acusaron', 'acoso'], 'TWEET5': ['estudiantes', 'imgenieria', 'quimica', 'universidad', 'autonoma', 'yucatan', 'pusieron', 'mismos', 'producir', 'gel', 'antibacterial', 'abastecer', 'necesidades', 'universidad'], 'TWEET6': ['fata', 'morgana', 'ilusiã³n', 'ã³ptica', 'debe', 'inversiã³n', 'temperatura', 'separaciã³n', 'regular', 'aire', 'caliente', 'air

In [0]:
dicc_termns = {}

for text in dicc_texts:
    for word in dicc_texts[text]:
#        print("EVALUAR:", word, "EN", text)
        if(word in dicc_termns):#incrementar palabras al diccionario
            dicc_termns[word] = dicc_termns[word] + 1
#            print(word, "IN", "dicc_termns")
        elif(word not in dicc_termns):#agregar palabras al diccionario        
            dicc_termns[word] = 1
#            print(word, "NOT IN", "dicc_termns")            
print(len(dicc_termns))
dicc_termns

253


{'19': 1,
 '2020': 1,
 '22': 1,
 '39': 1,
 '50': 1,
 '70': 1,
 'abastecer': 1,
 'abcâ': 1,
 'abre': 1,
 'acaba': 1,
 'accionistas': 1,
 'acoso': 1,
 'actuar': 1,
 'acusaron': 1,
 'administraciã³n': 1,
 'admiraciã³n': 1,
 'afuera': 1,
 'ahi': 1,
 'ahora': 1,
 'aire': 2,
 'alumnas': 1,
 'amlo': 1,
 'amos': 1,
 'andres': 1,
 'antibacterial': 1,
 'artista': 1,
 'atrapadas': 1,
 'autonoma': 1,
 'aventuras': 1,
 'aã': 2,
 'bachilleres': 1,
 'balacera': 1,
 'banda': 1,
 'bar': 1,
 'barcelona': 1,
 'bot': 1,
 'buena': 1,
 'cahiers': 1,
 'caliente': 1,
 'cambiando': 1,
 'cambiar': 1,
 'canal': 1,
 'cancelando': 1,
 'cara': 1,
 'caracas': 1,
 'caricaturista': 1,
 'carteles': 1,
 'centro': 1,
 'cerca': 1,
 'charla': 1,
 'checa': 1,
 'china': 1,
 'chulula': 1,
 'cine': 1,
 'cinã': 1,
 'colectiva': 1,
 'colegio': 1,
 'compaã': 1,
 'complica': 1,
 'confianza': 1,
 'conflicto': 1,
 'consecuencias': 1,
 'contacto': 1,
 'covid': 1,
 'covid19': 1,
 'creer': 1,
 'ctimas': 1,
 'cuarentena': 2,
 'cuenta': 

In [0]:
print(dicc_termns)

{'madrugada': 1, 'sabado': 1, 'dos': 1, 'hombres': 2, 'mujer': 1, 'resultaron': 1, 'lesionados': 1, 'tras': 1, 'registrarse': 1, 'balacera': 1, 'afuera': 1, 'bar': 1, 'ubicado': 1, 'zona': 1, 'centro': 1, 'san': 1, 'andres': 1, 'chulula': 1, 'puebla': 1, 'china': 1, 'derrumba': 1, 'hotel': 1, 'mantenia': 1, 'decenas': 1, 'personas': 2, 'cuarentena': 2, 'contacto': 1, 'infectados': 1, 'covid': 1, '19': 1, 'habla': 1, 'unas': 1, '70': 1, 'atrapadas': 1, 'escombros': 1, 'banda': 1, 'hacia': 1, 'creer': 1, 'perro': 1, 'enfermo': 1, 'necesitaban': 1, 'dinero': 1, 'vacunas': 1, 'estudiantes': 2, 'colegio': 1, 'bachilleres': 1, '39': 1, 'nazareno': 1, 'etla': 1, 'oaxaca': 1, 'alumnas': 1, 'encararon': 1, 'exhibieron': 1, 'carteles': 1, 'maestro': 1, 'acusaron': 1, 'acoso': 1, 'imgenieria': 1, 'quimica': 1, 'universidad': 2, 'autonoma': 1, 'yucatan': 1, 'pusieron': 1, 'mismos': 1, 'producir': 1, 'gel': 1, 'antibacterial': 1, 'abastecer': 1, 'necesidades': 1, 'fata': 1, 'morgana': 1, 'ilusiã³n'

**Matriz Término Documento (binario)**

In [0]:
matrix = np.zeros((len(dicc_texts), len(dicc_termns)))

In [0]:
print(matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
i = 0
j = 0

for word_termns in dicc_termns: #dicc_termns todos los términos
#    print()
    for word_texts in dicc_texts: #dicc_texts todos los textos
#        print("EVALUAR:", word_termns, "EN: ", word_texts)
        if(word_termns in dicc_texts[word_texts]): #si está
            print(word_termns, "IN", word_texts)
            
            matrix[j, i] = 1
            
        elif(word_termns not in dicc_texts[word_texts]): # si no está
            print(word_termns, "NOT IN", word_texts)
            
            matrix[j, i] = 0
            
            
        print("se agregó: ", matrix[j,i], "en: ", j, i)
            
        j = j + 1
        
    j = 0
    i = i + 1

Streaming output truncated to the last 5000 lines.
se agregó:  0.0 en:  0 128
amlo NOT IN TWEET2
se agregó:  0.0 en:  1 128
amlo NOT IN TWEET3
se agregó:  0.0 en:  2 128
amlo NOT IN TWEET4
se agregó:  0.0 en:  3 128
amlo NOT IN TWEET5
se agregó:  0.0 en:  4 128
amlo NOT IN TWEET6
se agregó:  0.0 en:  5 128
amlo NOT IN TWEET7
se agregó:  0.0 en:  6 128
amlo NOT IN TWEET8
se agregó:  0.0 en:  7 128
amlo NOT IN TWEET9
se agregó:  0.0 en:  8 128
amlo IN TWEET10
se agregó:  1.0 en:  9 128
amlo NOT IN TWEET11
se agregó:  0.0 en:  10 128
amlo NOT IN TWEET12
se agregó:  0.0 en:  11 128
amlo NOT IN TWEET13
se agregó:  0.0 en:  12 128
amlo NOT IN TWEET14
se agregó:  0.0 en:  13 128
amlo NOT IN TWEET15
se agregó:  0.0 en:  14 128
amlo NOT IN TWEET16
se agregó:  0.0 en:  15 128
amlo NOT IN TWEET17
se agregó:  0.0 en:  16 128
amlo NOT IN TWEET18
se agregó:  0.0 en:  17 128
amlo NOT IN TWEET19
se agregó:  0.0 en:  18 128
amlo NOT IN TWEET20
se agregó:  0.0 en:  19 128
estã NOT IN TWEET1
se agregó:  

In [0]:
matrix

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [0]:
matrix.shape

(20, 253)

In [0]:
matrix[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [0]:
a = 0
b = 0

In [0]:
for vectorA in matrix:
  for vectorB in matrix:
    if (a < b):
      res = dot(matrix[a],matrix[b])/(norm(matrix[a])*norm(matrix[b]))
      print("matrix[", a, "] vs matrix [", b, "]: ", res)
    b = b + 1
  b = 0
  a = a + 1

matrix[ 0 ] vs matrix [ 1 ]:  0.0
matrix[ 0 ] vs matrix [ 2 ]:  0.0
matrix[ 0 ] vs matrix [ 3 ]:  0.0
matrix[ 0 ] vs matrix [ 4 ]:  0.0
matrix[ 0 ] vs matrix [ 5 ]:  0.0
matrix[ 0 ] vs matrix [ 6 ]:  0.0
matrix[ 0 ] vs matrix [ 7 ]:  0.0
matrix[ 0 ] vs matrix [ 8 ]:  0.0
matrix[ 0 ] vs matrix [ 9 ]:  0.0
matrix[ 0 ] vs matrix [ 10 ]:  0.0
matrix[ 0 ] vs matrix [ 11 ]:  0.0
matrix[ 0 ] vs matrix [ 12 ]:  0.0
matrix[ 0 ] vs matrix [ 13 ]:  0.05923488777590923
matrix[ 0 ] vs matrix [ 14 ]:  0.0
matrix[ 0 ] vs matrix [ 15 ]:  0.0
matrix[ 0 ] vs matrix [ 16 ]:  0.0
matrix[ 0 ] vs matrix [ 17 ]:  0.0
matrix[ 0 ] vs matrix [ 18 ]:  0.0
matrix[ 0 ] vs matrix [ 19 ]:  0.0
matrix[ 1 ] vs matrix [ 2 ]:  0.0
matrix[ 1 ] vs matrix [ 3 ]:  0.0
matrix[ 1 ] vs matrix [ 4 ]:  0.0
matrix[ 1 ] vs matrix [ 5 ]:  0.0
matrix[ 1 ] vs matrix [ 6 ]:  0.0
matrix[ 1 ] vs matrix [ 7 ]:  0.0
matrix[ 1 ] vs matrix [ 8 ]:  0.0
matrix[ 1 ] vs matrix [ 9 ]:  0.0
matrix[ 1 ] vs matrix [ 10 ]:  0.0
matrix[ 1 ] vs matrix